### ISSUE TITLE
你的AAC系列文章写的很好，后面还会更新其他组件的文章吗

### ISSUE THREAD

**Issue by xurui1995** [AlanCheen/FullStackNotes#2]

**Comment by czn6** [comment]
谢谢你的认可，后面很难说。

因为我把我想学的都学了，没写的只有 DataBinding 了，但是我觉得这个原理好像没什么好讲的呢。

**Comment by xurui1995** [comment]
> 谢谢你的认可，后面很难说。
> 
> 因为我把我想学的都学了，没写的只有 DataBinding 了，但是我觉得这个原理好像没什么好讲的呢。

WorkManager这部分呢，光看Google IO上介绍感觉还是挺香的

**Comment by yihuajia** [comment]
话说关于ViewModel那里的实现在新版本中已经更改了

**Comment by czn6** [comment]
@xurui1995 WorkManager 我工作中没用到 好奇心不大-0- 没有学习

**Comment by czn6** [comment]
@yihuajia 我写的是基于 1.1.1 的版本，因为项目没用到 androidx 所以- -，你说的是哪个版本呀？有什么核心变动吗？

**Comment by yihuajia** [comment]
@AlanCheen 2.0.0版本的，主要是把HolderFragment去掉了

**Comment by czn6** [comment]
那它是怎么再保存 ViewModel 的呢？

**Comment by yihuajia** [comment]
@AlanCheen 
FragmentActivity中有一个静态内部类NonConfigurationInstances---ViewModelStore,onCreate时从NonConfigurationInstances中取出ViewModelStore(如果存在的话)，ViewModelStore中是直接通过一个HashMap来保存的，在onDestory之后会clear。

**Comment by czn6** [comment]
@yihuajia 感谢
